### ISSUE TITLE
fail while build

### ISSUE THREAD

**Issue by nickpp** [WebsiteBeaver/CordovaCall#26]
After installing the plugin i receive. Build fails even before entering the code. Just after the install. 

/Users/user/MyProjects/cordova/dialer/platforms/android/src/com/dmarc/cordovacall/CordovaCall.java:66: error: cannot find symbol
        if(android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {

**Comment by D-Marc1** [comment]
Please post your logcat and Android version. Also, try starting a new project, as it could be another plugin conflicting with CordovaCall. [This](https://github.com/phonegap/phonegap-plugin-push/issues/1115) might help you too.

**Comment by dmarcs** [comment]
@nickpp Thanks for reporting this error. It should be fixed in 913da12. Uninstall and readd CordovaCall 1.1.3 with

```
cordova plugin rm cordova-call
cordova plugin add cordova-call
```
The reason this happened is because you have an older version of the Android SDK. It didn't happen for me because I have the latest SDK. android.os.Build.VERSION_CODES.O is a constant that your version of the SDK doesn't recognize, so I replaced it with 26 which is what the constant equals.

**Comment by nickpp** [comment]
changing the constant to 26 as suggested, did not solve the problem - but I have changed platforms/android/project.properties  target=android-26. Solved the problem. Thanks!

**Comment by dmarcs** [comment]
Glad it works! There were two instances of `android.os.Build.VERSION_CODES.O`, so maybe you only changed one of them. If you upgraded to 1.1.3 then both instances are replaced, and you shouldn't get the `cannot find symbol` error.
